name: boilerplate_annotations
description: This package contains annotations for boilerplate_generators
version: 1.1.0
homepage: https://github.com/KirsApps/boilerplate_annotations

environment:
  sdk: '>=2.17.0 <3.0.0'