name: boilerplate_annotations
description: This package contains annotations for boilerplate_generators
version: 2.0.1
homepage: https://github.com/KirsApps/boilerplate_annotations


environment:
  sdk: '>=3.0.0 <4.0.0'